<?php
/**
 * @file
 * Code for the Open Atrium Site Map feature.
 */

include_once 'oa_sitemap.features.inc';
/**
 * @file
 * Code for the OpenAtrium Sitemap.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function oa_sitemap_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function oa_sitemap_theme() {
  return array(
    'oa_sitemap_show' => array(
      'template' => 'oa-sitemap-show',
      'variables' => array(
        'node' => NULL,
        'children' => NULL,
        'sections' => NULL,
      ),
      'path' => drupal_get_path('module', 'oa_sitemap') . '/templates',
    ),
  );
}

/**
 * Main helper function to render a specific space row in the sitemap
 * Recursively calls for subspaces
 * @param $node, node object or nid
 * @param $icons, array of section type images keyed by tid
 * @param $index, start at 0
 * @param $depth, start at 0
 *
 */
function oa_sitemap_space_map($node, $icons = array(), &$index = 0, $depth = 0) {
  if (is_numeric($node)) {
    $node = node_load($node);
  }
  $nid = !empty($node) ? $node->nid : 0;

  $children = oa_core_get_groups_by_parent($nid);
  foreach ($children as $key => $child) {
    $subspace = node_load($child);
    $children[$key] = $subspace;
  }

  $sections = oa_core_space_sections($nid, 1, FALSE, array('field_oa_section|tid'));
  $section_links = array();
  foreach ($sections as $section) {
    $id = $section->field_oa_section_tid;
    $section_links[] = array(
      'link' => l($section->title, 'node/' . $section->nid),
      'icon' => !empty($icons[$id]) ? $icons[$id] : '',
      'class' => 'oa_section',
      'title_class' => 'oa_section_title',
    );
  }

  if (!empty($node)) {
    $section_links[] = array(
      'link' => l(t('New Section'), 'wizard/nojs/add/oa-section', array(
        'attributes' => array('class' => 'ctools-use-modal'))),
      'icon' => $icons[0],
      'class' => 'oa_section',
      'title_class' => 'oa_section_title',
    );
  }


  $index++;
  $vars = array(
    'link' => !empty($node) ? l('<span>' . check_plain($node->title) . '</span>', 'node/' . $node->nid, array('html'=>true)) : l(t('Home'), '<front>'),
    'sections' => $section_links,
    'depth' => $depth,
    'index' => $index,
    'class' => 'oa_space_wrapper item',
    'title_class' => 'oa_space_title',
  );

  $subspaces = array();
  foreach ($children as $subspace) {
    $subspaces[] = oa_sitemap_space_map($subspace, $icons, $index, $depth+1);
  }

  $index++;
  $new_space_vars = array(
    'link' => l('<span>' . t('New Space') . '</span>', 'wizard/nojs/add/oa-space', array(
      'attributes' => array('class' => 'ctools-use-modal'),
      'html'       => 'true')),
    'sections' => array(),
    'subspaces' => array(),
    'depth' => "$depth",
    'index' => $index,
    'class' => 'oa_space_wrapper item',
    'title_class' => 'oa_new_space_title', // allows link to work directly
    'icon' => $icons[0],
  );
  $subspaces[] = theme('oa_sitemap_show', $new_space_vars);

  $vars['subspaces'] = $subspaces;
  $output = theme('oa_sitemap_show', $vars);

  return $output;
}
